# Table of Contents
 <p><div class="lev1 toc-item"><a href="#引言：Numpy是什么" data-toc-modified-id="引言：Numpy是什么-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>引言：Numpy是什么</a></div><div class="lev1 toc-item"><a href="#：Numpy-Basics" data-toc-modified-id="：Numpy-Basics-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>：Numpy Basics</a></div><div class="lev2 toc-item"><a href="#一些小例子" data-toc-modified-id="一些小例子-21"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>一些小例子</a></div><div class="lev2 toc-item"><a href="#如何生成数组：" data-toc-modified-id="如何生成数组：-22"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>如何生成数组：</a></div><div class="lev2 toc-item"><a href="#如何输出数组：" data-toc-modified-id="如何输出数组：-23"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>如何输出数组：</a></div><div class="lev4 toc-item"><a href="#注意：如果数组太大不能被完全输出出来，Numpy会自动跳过中间的部分，仅仅显示两端的数据；但是如果你想打印出所有的数据，你可以通过以下命令来设置：" data-toc-modified-id="注意：如果数组太大不能被完全输出出来，Numpy会自动跳过中间的部分，仅仅显示两端的数据；但是如果你想打印出所有的数据，你可以通过以下命令来设置：-2301"><span class="toc-item-num">2.3.0.1&nbsp;&nbsp;</span><font color="red">注意：</font>如果数组太大不能被完全输出出来，Numpy会自动跳过中间的部分，仅仅显示两端的数据；但是如果你想打印出所有的数据，你可以通过以下命令来设置：</a></div><div class="lev2 toc-item"><a href="#Numpy的基础Oprerations" data-toc-modified-id="Numpy的基础Oprerations-24"><span class="toc-item-num">2.4&nbsp;&nbsp;</span>Numpy的基础Oprerations</a></div><div class="lev3 toc-item"><a href="#需要注意的是，一般算术上的operations对于Numpy-而言是基于elements的" data-toc-modified-id="需要注意的是，一般算术上的operations对于Numpy-而言是基于elements的-241"><span class="toc-item-num">2.4.1&nbsp;&nbsp;</span><font color="red">需要注意的是，一般算术上的operations对于Numpy 而言是基于elements的</font></a></div><div class="lev3 toc-item"><a href="#注意：-当operate不同类型的数组时，结果的数据类型会自动匹配更一般" data-toc-modified-id="注意：-当operate不同类型的数组时，结果的数据类型会自动匹配更一般-242"><span class="toc-item-num">2.4.2&nbsp;&nbsp;</span>注意： 当operate不同类型的数组时，结果的数据类型会自动匹配更一般</a></div><div class="lev3 toc-item"><a href="#的或者说是更精确的数据类型" data-toc-modified-id="的或者说是更精确的数据类型-243"><span class="toc-item-num">2.4.3&nbsp;&nbsp;</span>的或者说是更精确的数据类型</a></div><div class="lev2 toc-item"><a href="#Numpy中的关于数组的一些一元操作" data-toc-modified-id="Numpy中的关于数组的一些一元操作-25"><span class="toc-item-num">2.5&nbsp;&nbsp;</span>Numpy中的关于数组的一些一元操作</a></div><div class="lev2 toc-item"><a href="#通用的函数" data-toc-modified-id="通用的函数-26"><span class="toc-item-num">2.6&nbsp;&nbsp;</span>通用的函数</a></div><div class="lev3 toc-item"><a href="#还有np.all,np.any.np.floor.np.ceil,np.clip,np.cov,np.diff,np.trace等函数，可以通过ipython-的魔法命令获得例如（np.all?）" data-toc-modified-id="还有np.all,np.any.np.floor.np.ceil,np.clip,np.cov,np.diff,np.trace等函数，可以通过ipython-的魔法命令获得例如（np.all?）-261"><span class="toc-item-num">2.6.1&nbsp;&nbsp;</span>还有np.all,np.any.np.floor.np.ceil,np.clip,np.cov,np.diff,np.trace等函数，可以通过ipython 的魔法命令获得例如（np.all?）</a></div><div class="lev2 toc-item"><a href="#Indexing-,Slicing-and-iterating" data-toc-modified-id="Indexing-,Slicing-and-iterating-27"><span class="toc-item-num">2.7&nbsp;&nbsp;</span>Indexing ,Slicing and iterating</a></div><div class="lev3 toc-item"><a href="#一维数组" data-toc-modified-id="一维数组-271"><span class="toc-item-num">2.7.1&nbsp;&nbsp;</span>一维数组</a></div><div class="lev2 toc-item"><a href="#形状操作（Shape-Manipulation）" data-toc-modified-id="形状操作（Shape-Manipulation）-28"><span class="toc-item-num">2.8&nbsp;&nbsp;</span>形状操作（Shape Manipulation）</a></div><div class="lev3 toc-item"><a href="#改变数组的形状" data-toc-modified-id="改变数组的形状-281"><span class="toc-item-num">2.8.1&nbsp;&nbsp;</span>改变数组的形状</a></div><div class="lev3 toc-item"><a href="#拼装数组" data-toc-modified-id="拼装数组-282"><span class="toc-item-num">2.8.2&nbsp;&nbsp;</span>拼装数组</a></div><div class="lev3 toc-item"><a href="#分割数组变为小的数组（Spliting-one-array-into-serveral-smaller-ones）" data-toc-modified-id="分割数组变为小的数组（Spliting-one-array-into-serveral-smaller-ones）-283"><span class="toc-item-num">2.8.3&nbsp;&nbsp;</span>分割数组变为小的数组（Spliting one array into serveral smaller ones）</a></div><div class="lev2 toc-item"><a href="#复制数组和内存视图（Copies-and-Views）" data-toc-modified-id="复制数组和内存视图（Copies-and-Views）-29"><span class="toc-item-num">2.9&nbsp;&nbsp;</span>复制数组和内存视图（Copies and Views）</a></div><div class="lev3 toc-item"><a href="#非复制（No-Copy-at-all）" data-toc-modified-id="非复制（No-Copy-at-all）-291"><span class="toc-item-num">2.9.1&nbsp;&nbsp;</span>非复制（No Copy at all）</a></div><div class="lev3 toc-item"><a href="#视图或者浅拷贝（View-or-Shallow-Copy）" data-toc-modified-id="视图或者浅拷贝（View-or-Shallow-Copy）-292"><span class="toc-item-num">2.9.2&nbsp;&nbsp;</span>视图或者浅拷贝（View or Shallow Copy）</a></div><div class="lev3 toc-item"><a href="#深拷贝（Deep-Copy）" data-toc-modified-id="深拷贝（Deep-Copy）-293"><span class="toc-item-num">2.9.3&nbsp;&nbsp;</span>深拷贝（Deep Copy）</a></div><div class="lev2 toc-item"><a href="#函数以及方法综述（Functions-and-Method-Overview）" data-toc-modified-id="函数以及方法综述（Functions-and-Method-Overview）-210"><span class="toc-item-num">2.10&nbsp;&nbsp;</span>函数以及方法综述（Functions and Method Overview）</a></div><div class="lev2 toc-item"><a href="#关于数组下标的tricks(Fancy-Indexing-and-index-tricks)" data-toc-modified-id="关于数组下标的tricks(Fancy-Indexing-and-index-tricks)-211"><span class="toc-item-num">2.11&nbsp;&nbsp;</span>关于数组下标的tricks(Fancy Indexing and index tricks)</a></div><div class="lev3 toc-item"><a href="#数组切片的下标（Indexing-with-Arrays-of-Indices）" data-toc-modified-id="数组切片的下标（Indexing-with-Arrays-of-Indices）-2111"><span class="toc-item-num">2.11.1&nbsp;&nbsp;</span>数组切片的下标（Indexing with Arrays of Indices）</a></div><div class="lev3 toc-item"><a href="#具有Numpy特色的数组下标（Indexing-with-Boolean-Arrays）" data-toc-modified-id="具有Numpy特色的数组下标（Indexing-with-Boolean-Arrays）-2112"><span class="toc-item-num">2.11.2&nbsp;&nbsp;</span>具有Numpy特色的数组下标（Indexing with Boolean Arrays）</a></div><div class="lev3 toc-item"><a href="#is_（）函数" data-toc-modified-id="is_（）函数-2113"><span class="toc-item-num">2.11.3&nbsp;&nbsp;</span>is_（）函数</a></div><div class="lev2 toc-item"><a href="#线性运算（Linear-algebra）" data-toc-modified-id="线性运算（Linear-algebra）-212"><span class="toc-item-num">2.12&nbsp;&nbsp;</span>线性运算（Linear algebra）</a></div><div class="lev2 toc-item"><a href="#小贴士（Tips）" data-toc-modified-id="小贴士（Tips）-213"><span class="toc-item-num">2.13&nbsp;&nbsp;</span>小贴士（Tips）</a></div><div class="lev1 toc-item"><a href="#数据类型（Data-types）" data-toc-modified-id="数据类型（Data-types）-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>数据类型（Data types）</a></div><div class="lev2 toc-item"><a href="#Numpy中的数据类型" data-toc-modified-id="Numpy中的数据类型-31"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Numpy中的数据类型</a></div><div class="lev2 toc-item"><a href="#Array-Creation" data-toc-modified-id="Array-Creation-32"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>Array Creation</a></div><div class="lev3 toc-item"><a href="#Converting-Python-array_like-Obejectsto-Numpy-Arrays" data-toc-modified-id="Converting-Python-array_like-Obejectsto-Numpy-Arrays-321"><span class="toc-item-num">3.2.1&nbsp;&nbsp;</span>Converting Python array_like Obejectsto Numpy Arrays</a></div><div class="lev3 toc-item"><a href="#从硬盘读取数据" data-toc-modified-id="从硬盘读取数据-322"><span class="toc-item-num">3.2.2&nbsp;&nbsp;</span>从硬盘读取数据</a></div><div class="lev4 toc-item"><a href="#标准二进制格式" data-toc-modified-id="标准二进制格式-3221"><span class="toc-item-num">3.2.2.1&nbsp;&nbsp;</span>标准二进制格式</a></div><div class="lev4 toc-item"><a href="#普遍的ASCII格式" data-toc-modified-id="普遍的ASCII格式-3222"><span class="toc-item-num">3.2.2.2&nbsp;&nbsp;</span>普遍的ASCII格式</a></div><div class="lev2 toc-item"><a href="#I/O-with-Numpy" data-toc-modified-id="I/O-with-Numpy-33"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>I/O with Numpy</a></div><div class="lev3 toc-item"><a href="#with-genfromtxt--导入数据" data-toc-modified-id="with-genfromtxt--导入数据-331"><span class="toc-item-num">3.3.1&nbsp;&nbsp;</span>with <em>genfromtxt</em>  导入数据</a></div><div class="lev4 toc-item"><a href="#定义输入" data-toc-modified-id="定义输入-3311"><span class="toc-item-num">3.3.1.1&nbsp;&nbsp;</span>定义输入</a></div><div class="lev4 toc-item"><a href="#把字符串转化为有效的数据" data-toc-modified-id="把字符串转化为有效的数据-3312"><span class="toc-item-num">3.3.1.2&nbsp;&nbsp;</span>把字符串转化为有效的数据</a></div><div class="lev3 toc-item"><a href="#Numpy的文件操作（补充）" data-toc-modified-id="Numpy的文件操作（补充）-332"><span class="toc-item-num">3.3.2&nbsp;&nbsp;</span>Numpy的文件操作（补充）</a></div><div class="lev2 toc-item"><a href="#Indexing(下标)" data-toc-modified-id="Indexing(下标)-34"><span class="toc-item-num">3.4&nbsp;&nbsp;</span>Indexing(下标)</a></div><div class="lev3 toc-item"><a href="#脚标数组（Index-arrays）" data-toc-modified-id="脚标数组（Index-arrays）-341"><span class="toc-item-num">3.4.1&nbsp;&nbsp;</span>脚标数组（Index arrays）</a></div><div class="lev3 toc-item"><a href="#多维脚标数组（Indexing-Multi-dimentional-arrays）" data-toc-modified-id="多维脚标数组（Indexing-Multi-dimentional-arrays）-342"><span class="toc-item-num">3.4.2&nbsp;&nbsp;</span>多维脚标数组（Indexing Multi-dimentional arrays）</a></div><div class="lev3 toc-item"><a href="#布尔脚标数组（Boolean-or-&quot;mask&quot;-index-arrays）" data-toc-modified-id="布尔脚标数组（Boolean-or-&quot;mask&quot;-index-arrays）-343"><span class="toc-item-num">3.4.3&nbsp;&nbsp;</span>布尔脚标数组（Boolean or "mask" index arrays）</a></div><div class="lev3 toc-item"><a href="#组合脚标数组（Combining-index-arrays-with-slices）" data-toc-modified-id="组合脚标数组（Combining-index-arrays-with-slices）-344"><span class="toc-item-num">3.4.4&nbsp;&nbsp;</span>组合脚标数组（Combining index arrays with slices）</a></div><div class="lev3 toc-item"><a href="#结构化脚标工具（Structural-indexing-tools）" data-toc-modified-id="结构化脚标工具（Structural-indexing-tools）-345"><span class="toc-item-num">3.4.5&nbsp;&nbsp;</span>结构化脚标工具（Structural indexing tools）</a></div><div class="lev3 toc-item"><a href="#设置指定脚标的值（Assigning-values-to-indexed-arrays）" data-toc-modified-id="设置指定脚标的值（Assigning-values-to-indexed-arrays）-346"><span class="toc-item-num">3.4.6&nbsp;&nbsp;</span>设置指定脚标的值（Assigning values to indexed arrays）</a></div><div class="lev3 toc-item"><a href="#处理畸变的切片数量" data-toc-modified-id="处理畸变的切片数量-347"><span class="toc-item-num">3.4.7&nbsp;&nbsp;</span>处理畸变的切片数量</a></div><div class="lev2 toc-item"><a href="#广播（Broadcasting）" data-toc-modified-id="广播（Broadcasting）-35"><span class="toc-item-num">3.5&nbsp;&nbsp;</span>广播（Broadcasting）</a></div><div class="lev3 toc-item"><a href="#广播的一般规则" data-toc-modified-id="广播的一般规则-351"><span class="toc-item-num">3.5.1&nbsp;&nbsp;</span>广播的一般规则</a></div><div class="lev2 toc-item"><a href="#结构数组（Structured-Arrays）" data-toc-modified-id="结构数组（Structured-Arrays）-36"><span class="toc-item-num">3.6&nbsp;&nbsp;</span>结构数组（Structured Arrays）</a></div><div class="lev3 toc-item"><a href="#定义结构数据" data-toc-modified-id="定义结构数据-361"><span class="toc-item-num">3.6.1&nbsp;&nbsp;</span>定义结构数据</a></div><div class="lev3 toc-item"><a href="#访问权限和名字修改" data-toc-modified-id="访问权限和名字修改-362"><span class="toc-item-num">3.6.2&nbsp;&nbsp;</span>访问权限和名字修改</a></div><div class="lev3 toc-item"><a href="#一次访问多重区域" data-toc-modified-id="一次访问多重区域-363"><span class="toc-item-num">3.6.3&nbsp;&nbsp;</span>一次访问多重区域</a></div><div class="lev3 toc-item"><a href="#填充结构数组" data-toc-modified-id="填充结构数组-364"><span class="toc-item-num">3.6.4&nbsp;&nbsp;</span>填充结构数组</a></div><div class="lev3 toc-item"><a href="#记录数组" data-toc-modified-id="记录数组-365"><span class="toc-item-num">3.6.5&nbsp;&nbsp;</span>记录数组</a></div><div class="lev1 toc-item"><a href="#Cython（提高计算效率，Numpy的利器）" data-toc-modified-id="Cython（提高计算效率，Numpy的利器）-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Cython（提高计算效率，Numpy的利器）</a></div>

# 引言：Numpy是什么

Numpy是针对科学计算的一个基础的python第三方包。它是一个可以提供多维数组对象的Python第三方包，可以广泛运用于数学计算，逻辑计算，形状操作，数据按序排列、选择，I/O，傅里叶变化，基础的线性代数运算，基础的统计操作，随机模拟等等

Numpy数组的__核心__是_ndarray_对象，它将n维的数组压缩成一个友好均匀的数据类型，并且可以通过编写代码来对这些_ndarray_对象进行多种操作。值得注意的是，Numpy和标准Python数组存在一些__重要的__的<font color="red">__差异__</font>

- Numpy数组一旦创建出来，大小固定不变了，不想传统的Python中的list对象（可以动态变化）。改变_ndarray_的大小将会创造一个新的数组对象，并且删除原有的数组对象；
- Numpy的数组单元被声明为同样的数据类型时，将在内存中有同样的大小。有一种情况列外：一旦数据类型声明为_object_，（pyhton，当然也包括Numpy）数组中可以存在不同大小的数组单元；
- Numpy可以促进大数据的数值计算和其他类型的操作。典型的就是，采用Numpy的某些操作比Python内置的数组方法效率更好，而且代码量很小；
- 基于Python开发的许多科学数据计算的第三方包都在使用Numpy；

在科学计算中，数组的大小和运算速度被十分看重。举一个简单的例子来说，对一个一维数组中的所有元素都乘上一个数，得到一个同样长度的数组结果。如果我们用Python代码来写，我们可以这样：

这个结果显然是正确的，但是如果_a_和_b_同时包含几百万个数据量呢，我们用Python做循环的时候需要花费极大的开销的。我们可以通过C代码来完成同样的任务，效率比Python更高。（需要澄清的是，我们忽略变量的声明和初始化，内存分配等等）

但是随着我们数据维数的增加，代码的工作量也变大了，同样我们用C代码来做演示：


Numpy给了我们最好的解决方法：在Numpy默认模式下，对数组的操作是element-by-element,而且运算速度比之前编译的C代码速度更快：
c=a*b

由此可见，Numpy的风格更简单！

# ：Numpy Basics

- 在Numpy中__dimensions__被称为__axes__，轴的数量被称为__rank__

In [2]:
 import numpy as np

In [3]:
np.ndarray.ndim#数组的维数
np.ndarray.shape  #数组的形状
np.ndarray.size   #数组中所有元素的数量
np.ndarray.dtype #可以使用python自带的格式，也可以使用Numpy自己自己的数据类型np.int32,np.int16,np.float64等等
np.ndarray.itemsize #每一个数组元素在内存中所占的字节数
np.ndarray.data#缓冲区中包含该数组的实际个数



<attribute 'data' of 'numpy.ndarray' objects>

## 一些小例子

In [117]:
a=np.arange(15).reshape(3,5)

In [118]:
a


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [6]:
a.ndim

2

In [7]:
a.dtype.name

'int32'

In [8]:
a.itemsize

4

In [9]:
a.size

15

In [10]:
type(a)

numpy.ndarray

In [11]:
b=np.array([6,7,8])

In [12]:
type(b)

numpy.ndarray

## 如何生成数组：

<font color="red">常犯的错误：</font>np.array()是一个函数，在该函数需要的形参不是多个数值参数，而是一系列youlist组成的参数

例子如下：


In [13]:
a=np.array(1,2,3,4)# 错误形式

ValueError: only 2 non-keyword arguments accepted

In [ ]:
a=np.array([1,2,3,4])#正确形式
a

- 在创建数组的同时可以指定数据类型，即__dtype__
- 在创建数组时，可以采用_list_形式，也可以采用_tuple_类型结果都是一样的。

In [ ]:
b=np.array([[1,2,3,4],[5,6,7,8]],dtype=np.float64)
b

In [ ]:
b=np.array([(1,2,3,4),(5,6,7,8)],dtype=np.int32)

In [ ]:
b

In [ ]:
b=np.array([(1,2,3,4),(5,6,7,8)],dtype=complex)
b

In [ ]:
b=np.array([(1,2,3,4),(5,6,7,8)],dtype=complex)
b

大多数情形下，数组具体的元素是不知道的，但是数组的大小，形状是给定的。因此，Numpy提供了几个函数来创建初始的__占位符（placeholder）__内容

- __np.zeros__  创建全0数组

In [ ]:
np.zeros((3,4))

- __np.ones__ 创建全1数组

In [ ]:
np.ones((2,3,4),dtype=np.int16)

- __np.empty__创建随机空数组，数组初始化的值取决于内存的状态

In [ ]:
np.empty((2,3))

- __np.arange__  创建序列化数组,可以接受浮点型，这点和python内置的range函数还是有一定区别的

In [ ]:
np.arange(10,30,5)

In [ ]:
np.arange(0,2,0.1)

- __np.linspace__ 创建指定个数的序列化数组，step取决于Numpy；

In [ ]:
np.linspace(0,2,9)

- __np.zeros_like__等这些函数的用法： 

In [ ]:
x=np.arange(15).reshape(5,3)
x.astype(float)

In [ ]:
y=np.zeros_like(x)
y.dtype

- __np.random__的一些常见用法

In [ ]:
np.random.rand(4,5)

In [ ]:
np.random.randn(2,3)##随机数

In [ ]:
np.fromfunction(lambda i,j :i==j,(3,3),dtype=int)

In [ ]:
np.fromfunction(lambda i,j:i+j,(4,4),dtype=float)#采用广播形式啊

##  如何输出数组： 

- 最后的axis被从左往右打印出来
- 倒数第二个axis被从上到下打印出来
- 剩下的axis被从上到下打印出来，相邻slice中间被空行隔开

In [ ]:
a=np.arange(6)
a

In [ ]:
b=np.arange(12).reshape(4,3)
b

In [ ]:
c=np.arange(24).reshape(2,3,4)
c

#### <font color="red">注意：</font>如果数组太大不能被完全输出出来，Numpy会自动跳过中间的部分，仅仅显示两端的数据；但是如果你想打印出所有的数据，你可以通过以下命令来设置：

## Numpy的基础Oprerations

### <font color="red">需要注意的是，一般算术上的operations对于Numpy 而言是基于elements的
</font>

In [ ]:
a=np.array([20,30,40,50])

In [ ]:
a

In [ ]:
b=np.arange(4)
b


In [ ]:
c=a-b

In [ ]:
c

In [ ]:
b**2

In [ ]:
10*np.sin(a)

In [ ]:
a<35

- 注意矩阵相乘和Numpy基于element的区别

In [ ]:
A=np.array([[1,1],
          [0,1]])

In [ ]:
B=np.array([[2,0],
           [3,4]])

In [ ]:
A*B

In [ ]:
A.dot(B)

In [ ]:
np.dot(A,B)


- 类似C语言，Numpy也有自加等运算

In [ ]:
a=np.ones((2,3),dtype=int)
b=np.random.random((2,3))

In [ ]:
a*=3

In [ ]:
a

In [ ]:
b+=a

In [ ]:
b

In [ ]:
a+=b# b不会从float类型转化为int类型，只会从int类型转为float类型

### 注意： 当operate不同类型的数组时，结果的数据类型会自动匹配更一般

### 的或者说是更精确的数据类型

In [ ]:
from numpy import pi
a=np.ones(3,dtype=np.int32)
b=np.linspace(0,pi,3)

In [ ]:
b.dtype.name

In [ ]:
c=a+b
c

In [ ]:
c.dtype.name

In [ ]:
d=np.exp(c*1j)
d

In [ ]:
d.dtype.name

## Numpy中的关于数组的一些一元操作

In [ ]:
a=np.random.random((2,3))

In [ ]:
a

In [ ]:
a.sum()

In [ ]:
a.max()

In [ ]:
a.min()

In [ ]:
a.cumsum(axis=1)

In [ ]:
a.cumsum(axis=0)

## 通用的函数

- Numpy自身提供了一些相似的数学函数，例如sin,cos，exp等。在Numpy中这些统统被称为“universal functions”(ufunc),这些函数是针对数组中的元素进行操作的，输出结果还是一个数组

In [ ]:
B=np.arange(3)
B

In [ ]:
np.exp(B)

In [ ]:
np.sqrt(B)

In [ ]:
np.sin(B)

In [ ]:
C=np.array([[1,2,3]])

In [ ]:
np.add(B,C)

### 还有np.all,np.any.np.floor.np.ceil,np.clip,np.cov,np.diff,np.trace等函数，可以通过ipython 的魔法命令获得例如（np.all?）

## Indexing ,Slicing and iterating

###  一维数组

In [ ]:
a=np.arange(10)**3
a

In [ ]:
a[2]

In [ ]:
a[2:5]

In [ ]:
a[-1]

In [ ]:
a[:6:2]

In [ ]:
a[:6:2]=-1000

In [ ]:
a[::-1]#相当于inverse

In [ ]:
np.invert(a)+1

In [ ]:
for i in a:
    print(i**(1/3.))

- 对于多维数组而言，一个index代表一个轴上的所有数据的集合

In [ ]:
def f(x,y):
    return 10*x+y

In [ ]:
b=np.fromfunction(f,(5,4),dtype=np.int32)

In [ ]:
b

In [ ]:
b[2,3]

In [ ]:
b[0:5,1]

In [ ]:
b[:,1]

In [ ]:
b[1:3,:]

In [ ]:
b[-1]

- 对于有许多冒号的，可以写成x[1,2,...]等同于x[1,2,:,:,:]（假设x有5个轴）

In [ ]:
c=np.array([[[0,1,2],
            [10,12,13]],
           [[100,101,102],
           [110,112,113]]])

In [ ]:
c.shape

In [ ]:
c[1,...]

In [ ]:
c[...,2]

- 迭代多维数组可以通过第一周也就是0 axis

In [ ]:
for row in b:
    print(row)
    

- 如果你想获得每一个元素，你可以像如下所示的做法

In [ ]:
for i in b.flat:
    print(i)

## 形状操作（Shape Manipulation）


### 改变数组的形状

In [ ]:
a=np.floor(10*np.random.random((3,4)))

In [ ]:
a


In [ ]:
a.shape

- 下列的命令都可以改变数组的形状


In [ ]:
a.ravel()

In [ ]:
a.shape=(6,2)

In [ ]:
a

In [ ]:
a.T

- <font color="red">注意：</font> reshape并不改变原始数组的形状，而resize改变原始数组的形状

In [ ]:
a


In [ ]:
a.reshape(2,6)

In [ ]:
a

In [ ]:
a.resize(2,6)

In [ ]:
a

- <font color="red">注意：</font>数组的某一维度上的值为负数时，则说明Numpy会自动计算该维度上的值

In [ ]:
a.reshape(6,-1)

### 拼装数组

In [ ]:
a=np.floor(10*np.random.random((2,2)))
a


In [ ]:
b=np.floor(10*np.random.random((2,2)))
b

In [ ]:
np.vstack((a,b))

In [ ]:
np.hstack((a,b))

- column_stack()函数的用法

In [ ]:
from numpy import newaxis

In [ ]:
np.column_stack((a,b))

In [ ]:
a=np.array([4.,2.])
b=np.array([2.,8.])

In [ ]:
a[:,newaxis]

In [ ]:
np.column_stack((a[:,newaxis],b[:,newaxis]))

In [ ]:
np.vstack((a[:,newaxis],b[:,newaxis]))

In [ ]:
np.hstack((a[:,newaxis],b[:,newaxis]))

<font color="red">注意：</font>r\_和c\_和__hastack__与__vstack__是相似的命令，是沿着某一个轴进行的组装；


In [ ]:
np.r_[a,b]

In [ ]:
np.c_[a,b]

### 分割数组变为小的数组（Spliting one array into serveral smaller ones）

In [ ]:
a=np.floor(10*np.random.random((2,12)))

In [ ]:
a

In [ ]:
np.hsplit(a,4)

In [ ]:
np.vsplit(a,2)

In [ ]:
np.hsplit(a,3)

## 复制数组和内存视图（Copies and Views）

### 非复制（No Copy at all）

In [ ]:
a=np.arange(12)

In [ ]:
b=a


In [ ]:
b is a

In [ ]:
b.shape=3,4

In [ ]:
a.shape

### 视图或者浅拷贝（View or Shallow Copy）

In [ ]:
c=a.view()

In [ ]:
c is a

In [ ]:
c.base is a

In [ ]:
c.flags.owndata

In [ ]:
c.shape=2,6

In [ ]:
a.shape  ##a的形状没有改变

In [ ]:
c[0,4]=1234

In [ ]:
a       ##a的数据发生了改变

In [ ]:
s=a[:,1:3]

In [ ]:
s[:]=10 # s[:]是一个s的视图，注意s=10和s[:]=10的区别

In [ ]:
s=10

In [ ]:
a

In [ ]:
s

### 深拷贝（Deep Copy）

- 深拷贝就是在原有数据的基础上进行完全的拷贝并生成新的数组，两者在内存中的地址是完全不一样的

In [ ]:
d=a.copy()


In [ ]:
d is a

In [ ]:
id(a)

In [ ]:
id(d)

## 函数以及方法综述（Functions and Method Overview）

- <font size=4>创建数据</font>
    - arange
    - array
    - copy
    - empty
    - empty_like
    - eye
    - fromfile
    - fromfunction
    - identity
    - linspace
    - logspace
    - mgrid
    - ogrid
    - ones
    - ones_like
    - zeros
    - zeros_like

- <font size=4>类型转换（Converisons）</font>
    - ndarray.astype
    - atleast_1d
    - atleast_2d
    - atleast_3d
    - mat

- <font size=4>数组操作（Manipulation）</font>
    - array_split
    - column_stack
    - concatenate
    - diagonal
    - dsplit
    - dstack
    - hsplit
    - hstack
    - ndarray.item
    - newaxis
    - ravel
    - repeat
    - reshape
    - resize
    - squeeze
    - swapaxes
    - take
    - transpose
    - vsplit
    - vstack

- <font size=4>问题（Question)</font>
    - all
    - any
    - nonzero
    - where

- <font size=4>排序（Ordering）</font>
    - argmax
    - argmin
    - argsort
    - max
    - min
    - ptp
    - searchsorted
    - sort
    

- <font size=4>操作（Operations）</font>
    - choose
    - compress
    - cumprod
    - cumsum
    - inner
    - ndarray.fill
    - imag
    - prod
    - put
    - putmask
    - real
    - sum 

- <font size=4>基础统计（Basic Statistic）</font>
    - cov
    - mean
    - std
    - var
    

- <font size=4>基础线性代数（Basic Linear Algebra）</font>
    - cross
    - dot
    - outer
    - linalg.svd
    - vdot

## 关于数组下标的tricks(Fancy Indexing and index tricks)

### 数组切片的下标（Indexing with Arrays of Indices）

In [ ]:
a=np.arange(12)**2

In [ ]:
i=np.array([1,1,3,8,5])

In [ ]:
a[i]

In [ ]:
j=np.array([[3,4],
           [9,7]])


In [ ]:
a[j]

- <font color="red">注意：下面情况的例子比较特殊，请自己认真体会</font>

In [ ]:
palette=np.array([[0,0,0],
                 [255,0,0],
                 [0,255,0],
                 [0,0,255],
                 [255,255,255]])

In [ ]:
image=np.array([[0,1,2,0],
              [0,3,4,0]])

In [ ]:
palette[image]

- <font color="red">注意：除此之外，数组下标也可以超过一维</font>

In [ ]:
a=np.arange(12).reshape(3,4)

In [ ]:
a


In [ ]:
i=np.array([[0,1],
           [1,2]])

In [ ]:
j=np.array([[2,1],
           [3,3]])

In [ ]:
a[i,j]

In [ ]:
a[i,2]

In [ ]:
a[:,j]

- 除此之外，可以把下标打包成一个_list_

In [ ]:
l=[i,j]
a[l]

- 下面的使用数组下标的例子也很趣

In [ ]:
import numpy as np
time=np.linspace(20,145,5)

In [ ]:
data=np.sin(np.arange(20)).reshape(5,4)

In [ ]:
time

In [ ]:
data

In [ ]:
ind=data.argmax(axis=0)

In [ ]:
ind

In [ ]:
ind1=data.argmax(axis=1)

In [ ]:
ind1

In [ ]:
time_max=time[ind]

In [ ]:
time_max

In [ ]:
data_max=data[ind,range(data.shape[1])]

In [ ]:
data_max


In [ ]:
import numpy as np
np.all(data_max == data.max(axis=0))

- 你也可以采用下面的手段来进行赋值

In [ ]:
a=np.arange(5)

In [ ]:
a

In [ ]:
a[[1,3,4]]=0


In [ ]:
a

- 当然也可以这样

In [ ]:
a=np.arange(5)

In [ ]:
a

In [ ]:
a[[0,0,2]]=[1,2,3]

In [ ]:
a


### 具有Numpy特色的数组下标（Indexing with Boolean Arrays）

- 布尔数组下标的优越性

In [ ]:
a=np.arange(12).reshape(3,4)

In [ ]:
b=a>4

In [ ]:
b

In [ ]:
a[b]

- 下面这种用法是最吸引人的，可以把不需要的数据置为你想设置的数据，这里设置为0

In [ ]:
a[b]=0
a

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
def mandelbrot(h,w,maxit=20):
    y,x=np.ogrid[-1.4:1.4:h*1j,-2:0.8:w*1j]
    c=x+y*1j
    z=c
    divtime=maxit+np.zeros(z.shape,dtype=int)
    for i in range(maxit):
        z=z**2+c
        diverge=z*np.conj(z)>2**2
        div_now=diverge & (divtime==maxit)
        divtime[div_now]=i
        z[diverge]=2
    return divtime

In [ ]:
plt.imshow(mandelbrot(400,400))

In [ ]:
plt.show()

In [ ]:
np.ogrid? #创建数组

In [ ]:
np.conj? #返回共轭复数

- 第二种布尔数组的yongfa

In [ ]:
a=np.arange(12).reshape(3,4)
a

In [ ]:
b1=np.array([False,True,True])

In [ ]:
b2=np.array([True,False,True,False])

In [ ]:
a[b1,:]

In [ ]:
a[:,b2]

In [ ]:
a[b1,b2] #奇怪的行为

### is\_（）函数

- ix\_函数可以用来合并不同向量并去获得对于每一个n-uplet的结果

In [ ]:
a=np.array([2,3,4,5])
b=np.array([8,5,4])
c=np.array([5,4,6,8,3])

In [ ]:
ax,bx,cx=np.ix_(a,b,c)

In [ ]:
ax

In [ ]:
bx

In [ ]:
cx

In [ ]:
ax.shape,bx.shape,cx.shape

In [ ]:
result=ax+bx*cx

In [ ]:
result

In [ ]:
result[3,2,4]

In [ ]:
a[3]+b[2]*c[4]

## 线性运算（Linear algebra）

In [ ]:
a=np.array([[1.,2.],
           [3.,4.]])

In [ ]:
a

In [ ]:
print(a)

In [ ]:
a.transpose() #矩阵的转置

In [ ]:
np.linalg.inv(a) #特征值

In [ ]:
u=np.eye(2)

In [ ]:
u

In [ ]:
j=np.array([[0.,-1.],
           [1.,0.]])

In [ ]:
np.dot(j,j)

In [ ]:
np.trace(u) #矩阵的迹

In [ ]:
y=np.array([[5.],
           [7.]])

In [ ]:
np.linalg.solve(a,y)  #解线性方程组

In [ ]:
np.linalg.eig(j)

## 小贴士（Tips）

- Histograms

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
mu,sigma=2,0.5
v=np.random.normal(mu,sigma,10000)
plt.hist(v,bins=50,normed=1)# matplotlib version（plot）
plt.show()

In [ ]:
import matplotlib.pyplot as plt
mu,sigma=2,0.5
v=np.random.normal(mu,sigma,10000)
(n,bins)=np.histogram(v,bins=50,normed=True)  # Numpy version
plt.plot(.5*(bins[1:]+bins[:-1]),n)
plt.show()

# 数据类型（Data types）

## Numpy中的数据类型


In [ ]:
from IPython.display import Image

In [ ]:
Image(filename="C:/Users/徐凯龙/Desktop/datatype.PNG")


In [ ]:
from IPython.display import FileLink

In [ ]:
Image?

In [ ]:
import numpy as np

In [ ]:
x=np.float32(1.0)

In [ ]:
y=np.int_([1,2,3,4])

In [ ]:
type(y)

In [ ]:
y

In [ ]:
z=np.arange(3,dtype=np.uint8)

In [ ]:
z

In [ ]:
np.array([1,2,3],dtype="f")

- Numpy推荐使用 dtype objects定义：

In [ ]:
z.astype("f")

In [ ]:
np.int8(z)

- 注意以上我们使用Python的float 对象作为一个dtype.Numpy中int引用np.int\_,float引用np.float\_,bool引用np.\_。

In [ ]:
d=np.dtype(int)

In [ ]:
d

In [ ]:
np.issubdtype(d,int)

In [ ]:
np.issubdtype(d,float)

- python本身的float通常是64位浮点数，等效于np.float64,

In [ ]:
np.finfo

## Array Creation

- Conversion from other Python structures(eg.,lists,tuples)
- Intrinsic numpy array array creation objects(eg.,arange,ones,zeros,etc)
- Reading arrays from disk ,either from the standard or custom formats
- Creating arrays from raw bytes through the use of strings or buffers 
- Use of special library functions

### Converting Python array_like Obejectsto Numpy Arrays

In [ ]:
x=np.array([2,3,1,0])

In [ ]:
x=np.array([2,  3,  1,  0])

In [ ]:
x


In [ ]:
x=np.array([[1,2,0],
           [0.,0.],
           [1+1j,3.],])# 混合类型，注意混合类型的dtype=obeject

In [ ]:
x

- indices的奇妙用法

In [ ]:
np.indices((3,3))

 ### 从硬盘读取数据

- 这是最普遍的创建数组的形式。形式上来讲，数组的创建依赖于硬盘中数据格式，因此这一部分介绍关于怎么去处理各式各样的数据格式。

#### 标准二进制格式

- HDF5: Pytables
- FITS: PyFITS

#### 普遍的ASCII格式

- 逗号分隔符文件：CSV
- 更多的ascii文件可以采用Scipy提供的包文件

 ## I/O with Numpy

### with _genfromtxt_  导入数据

_genfromtxt_内部实现机制：

- 第一层循环：把文件中的每一行数据转化为字符串；
- 第二层循环：把相应的字符串转化为合适的数据类型

这种机制虽然比单层循环更慢，但是更加灵活。<font color="red">特别的</font>，_genfromtxt_可以处理缺失值，不像简单快速的_loadtxt_函数

#### 定义输入

_genfromtxt_只需要一个参数：数据来源。它可以是字符串，字符串组 ，或者一个生成器。当远程文件的URL传递进来时，文件会自动下载到当前工作目录下并打开

- 考虑到文件类型会是txt或者其他压缩文件。目前，该函数只支持_gzip_和_bz2_压缩文件

- _gentfromtxt_会跳过空行和注释行，_delimiter_参数用来定义怎么发生, _delimiter_默认是"  "(连续的空格或者tab都作为一个空格来处理)

In [14]:
import numpy as np
from io import BytesIO

In [15]:
data=b"1, 2, 3\n4, 5, 6"

In [16]:
np.genfromtxt(BytesIO(data),delimiter=",")

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

- 当我们处理变宽度的文件时，可以用一个给定的值来定义列，通常这种情况下，把_delimiter_设置为一个整数，或者一系列整数

In [17]:
data=b"1 2 3\n4 5 67\n567865 4"

In [18]:
np.genfromtxt(BytesIO(data),delimiter=(1,3,2))

array([[   1.,    2.,    3.],
       [   4.,    5.,   67.],
       [   5.,  678.,   65.]])

- 自动分割参数（autostrip argument）

In [19]:
data=b"1, abc , 2\n 3, xxx, 4"

In [20]:
np.genfromtxt(BytesIO(data),delimiter=",",dtype="|S5")

array([[b'1', b' abc ', b' 2'],
       [b'3', b' xxx', b' 4']], 
      dtype='|S5')

In [21]:
np.genfromtxt(BytesIO(data),delimiter=",",dtype="|S5",autostrip=True)

array([[b'1', b'abc', b'2'],
       [b'3', b'xxx', b'4']], 
      dtype='|S5')

- 注释参数（comment argument）

In [22]:
data=b"""
#skip me.
#skip me too
1,2
3,4
5,6# comments
7,8
#comments too
9,0




"""

In [23]:
np.genfromtxt(BytesIO(data),comments="#",delimiter=",")

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.],
       [ 9.,  0.]])

- <font color="red">非常有用的参数</font>：主要用于Skipping lines and choosing columns

In [24]:
data=b"0\n1\n2\n3\n4\n5\n6\n7\n8\n9\n0"

In [25]:
data

b'0\n1\n2\n3\n4\n5\n6\n7\n8\n9\n0'

In [26]:
np.genfromtxt(BytesIO(data),skip_header=3,skip_footer=5)

array([ 3.,  4.,  5.])

- The _usecols_ argument

In [27]:
data=b"1 2 3\n 4 5 6"

In [28]:
np.genfromtxt(BytesIO(data),usecols=(0,-1))

array([[ 1.,  3.],
       [ 4.,  6.]])

In [29]:
data=b"1 2 3\n4 5 6"

In [30]:
np.genfromtxt(BytesIO(data),names="a,b,c",usecols=("a","c"))

array([( 1.,  3.), ( 4.,  6.)], 
      dtype=[('a', '<f8'), ('c', '<f8')])

- 选择数据类型（Choosing the data type）

- <font color="red">注意：</font> _genfromtxt_默认的数据类型是float(dtype=float)

- 设置名字

In [31]:
data=BytesIO(b"1 2 3\n 4 5 6")

In [32]:
np.genfromtxt(data,dtype=[(_,int)for _ in "abc"])

array([(1, 2, 3), (4, 5, 6)], 
      dtype=[('a', '<i4'), ('b', '<i4'), ('c', '<i4')])

In [33]:
#还有一种更简单的形式是：
data=BytesIO(b"1 2 3 \n 4 5 6")
np.genfromtxt(data,names="A,B,C")

array([( 1.,  2.,  3.), ( 4.,  5.,  6.)], 
      dtype=[('A', '<f8'), ('B', '<f8'), ('C', '<f8')])

In [34]:
#列名直接来源于数据：
data=BytesIO(b"So it goes\n #a b c\n 1 2 3\n 4 5 6\n 7 8 9\n 12 13 14")

In [35]:
np.genfromtxt(data,skip_header=1,names=True)

array([(  1.,   2.,   3.), (  4.,   5.,   6.), (  7.,   8.,   9.),
       ( 12.,  13.,  14.)], 
      dtype=[('a', '<f8'), ('b', '<f8'), ('c', '<f8')])

 - 默认名字的值是None,如果我们给每一个值一个关键字，也就是键值对，将会覆盖掉原来的列名
 

In [36]:
data=BytesIO(b"1 2 3\n 4 5 6")

In [37]:
ndtype=[("a",int),("b",float),("c",int)]

In [38]:
names=["A","B","C"]

In [39]:
np.genfromtxt(data,names=names,dtype=ndtype)

array([(1,  2., 3), (4,  5., 6)], 
      dtype=[('A', '<i4'), ('B', '<f8'), ('C', '<i4')])

<font color="red">注意：</font>如果__names=None__,但是有需要结构类型，Numpy默认的列名是_"f%i"_,接连产生像_f0 _ f1 _这样的名字

In [40]:
data=BytesIO(b"1 2 3\n 4 5 6")

In [41]:
np.genfromtxt(data,dtype=(int ,float,int))

array([(1,  2., 3), (4,  5., 6)], 
      dtype=[('f0', '<i4'), ('f1', '<f8'), ('f2', '<i4')])

- 同样的方式，如果我们没有设置足够的列名，Numpy会自动补全列名（按默认值）

In [42]:
data=BytesIO(b"1 2 3\n 4 5 6")


In [43]:
np.genfromtxt(data,dtype=(int,float,int),names="a")

array([(1,  2., 3), (4,  5., 6)], 
      dtype=[('a', '<i4'), ('f0', '<f8'), ('f1', '<i4')])

- 如果我们想覆盖Numpy默认的列名，我们可以这样：

In [44]:
data=BytesIO(b"1 2 3\n 4 5 6")

In [45]:
np.genfromtxt(data,dtype=(int,"f",int),defaultfmt="var_%02i")

array([(1,  2., 3), (4,  5., 6)], 
      dtype=[('var_00', '<i4'), ('var_01', '<f4'), ('var_02', '<i4')])

#### 把字符串转化为有效的数据

In [46]:
convertfunc=lambda x:float(x.strip("%"))/100.
data=b"1, 2.3%, 45.\n 6, 78.9%, 0"
names=["i","p","n"]


In [47]:
np.genfromtxt(BytesIO(data),delimiter=",",names=names)

array([( 1.,  nan,  45.), ( 6.,  nan,   0.)], 
      dtype=[('i', '<f8'), ('p', '<f8'), ('n', '<f8')])

In [48]:
# np.genfromtxt(converters?)该函数有待解决！

- 缺失值处理

In [49]:
data=b"N/A,2,3\n4,,???"

In [50]:
import numpy as np
from io import BytesIO

In [51]:
kwargs=dict(delimiter=",",dtype=int,names="a,b,c",missing_values={0:"N/A","b":"",2:"???"},
            filling_values={0:0,"b":0,2:-999})

In [52]:
np.genfromtxt(BytesIO(data),**kwargs)

array([(0, 2,    3), (4, 0, -999)], 
      dtype=[('a', '<i4'), ('b', '<i4'), ('c', '<i4')])

### Numpy的文件操作（补充）

- ndarray 对象可以保存到磁盘文件并从磁盘文件加载。可用的IO功能有：
    - load()和save()函数处理Numpy二进制文件（带npy扩展名）
    - loadtxt()和savetxt()函数处理正常文本文件

<font color="red">注意：</font>Numpy为_ndarray_对象引入了一个简单的文本格式。这个_npy_文件在磁盘文件中，存储重建_ndarray_所需的数据、图形、_dtype_和其他信息，以便正确获取数组，即使该文件在具有不同架构的另一台机器上。

In [53]:
np.save?

In [54]:
a=np.array([1,2,3,4,5,6])
np.save("outfile",a)

In [55]:
np.load("outfile.npy")

array([1, 2, 3, 4, 5, 6])

_save()_和_load()_函数接受一个附加的布尔参数_allow_\__pickles_。Python中的_pickle_用于保存到磁盘文件或从磁盘文件读取之前，对对象进行序列化和反序列化

- _savetxt()_和_loadtxt()_函数的用法，就是以简单文本文件格式存储和获取数组数据

In [56]:
a=np.arange(1000)

In [57]:
np.savetxt("out.txt",a)

In [58]:
np.loadtxt("out.txt")

array([   0.,    1.,    2.,    3.,    4.,    5.,    6.,    7.,    8.,
          9.,   10.,   11.,   12.,   13.,   14.,   15.,   16.,   17.,
         18.,   19.,   20.,   21.,   22.,   23.,   24.,   25.,   26.,
         27.,   28.,   29.,   30.,   31.,   32.,   33.,   34.,   35.,
         36.,   37.,   38.,   39.,   40.,   41.,   42.,   43.,   44.,
         45.,   46.,   47.,   48.,   49.,   50.,   51.,   52.,   53.,
         54.,   55.,   56.,   57.,   58.,   59.,   60.,   61.,   62.,
         63.,   64.,   65.,   66.,   67.,   68.,   69.,   70.,   71.,
         72.,   73.,   74.,   75.,   76.,   77.,   78.,   79.,   80.,
         81.,   82.,   83.,   84.,   85.,   86.,   87.,   88.,   89.,
         90.,   91.,   92.,   93.,   94.,   95.,   96.,   97.,   98.,
         99.,  100.,  101.,  102.,  103.,  104.,  105.,  106.,  107.,
        108.,  109.,  110.,  111.,  112.,  113.,  114.,  115.,  116.,
        117.,  118.,  119.,  120.,  121.,  122.,  123.,  124.,  125.,
        126.,  127.,

 ## Indexing(下标)

 Numpy采用C-order下标。这意味着最后的下标在内存中可以更迅速的改变位置，不像Fortran和IDL(第一个下标在内存中可以更快的改变位置)

In [59]:
x=np.arange(10)

In [60]:
x[2:5]

array([2, 3, 4])

In [61]:
x[:-7]

array([0, 1, 2])

In [62]:
x[1:7:2]

array([1, 3, 5])

In [63]:
y=np.arange(35).reshape(5,7)

In [64]:
y[1:5:2,::3]

array([[ 7, 10, 13],
       [21, 24, 27]])

- 需要注意的是：数组的切片不是原始数组的copy，仅仅是原始数组的view

### 脚标数组（Index arrays）

<font color="red">注意的是：</font>对于所有的脚标数组的情形，返回的数组都是原始数组的copy,而不是一个view或者是切片

In [65]:
x=np.arange(10,1,-1)

In [66]:
x


array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [67]:
y=x[np.array([3,3,1,8])]

In [68]:
id(y)

1818759180736

In [69]:
id(x)

1818759142736

In [70]:
Y=x[1:3]

In [71]:
id(Y)

1818759180416

In [72]:
id(x)

1818759142736

- 当然了，负数脚标也可以工作的很好

In [73]:
x[np.array([3,3,-3,8])]

array([7, 7, 4, 2])

- 不能越界，否则会抛出IndexError

In [74]:
x[np.array([3,3,20])]

IndexError: index 20 is out of bounds for axis 0 with size 9

- 一般情况下，返回的数组形状和脚标数组的形状相同

In [75]:
x[np.array([[1,1],
           [2,3]])]

array([[9, 9],
       [8, 7]])

### 多维脚标数组（Indexing Multi-dimentional arrays）

- 尽管多数情形下不采用这种形式，但是针某些问题，这种形式还是十分有用的

In [76]:
y=np.arange(35).reshape(5,7)
y[np.array([0,2,4]),np.array([0,1,2])]

array([ 0, 15, 30])

In [77]:
y[np.array([0,2,4]),np.array([0,1])]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

In [78]:
y[np.array([0,2,4]),1]

array([ 1, 15, 29])

In [79]:
y[np.array([0,2,4])]

array([[ 0,  1,  2,  3,  4,  5,  6],
       [14, 15, 16, 17, 18, 19, 20],
       [28, 29, 30, 31, 32, 33, 34]])

### 布尔脚标数组（Boolean or "mask" index arrays）

In [80]:
b=y>20


In [81]:
y[b]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [82]:
b

array([[False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]], dtype=bool)

In [83]:
b[:,5]

array([False, False, False,  True,  True], dtype=bool)

In [84]:
y[b[:,5]]

array([[21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

<font color="red">注意：</font>通常情形下，布尔数组比脚标数组有更少的维数：

In [85]:
x=np.arange(30).reshape(2,3,5)

In [86]:
x

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [87]:
b=np.array([[True,True,False],
           [False,True,True]])

In [88]:
x[b]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

### 组合脚标数组（Combining index arrays with slices）

In [89]:
y[np.array([0,2,4]),1:3]

array([[ 1,  2],
       [15, 16],
       [29, 30]])

- 效果上，slice等同于np.array([1,2])

In [90]:
y=np.arange(35).reshape(5,7)
b=y>20
y[b[:,5],1:3]

array([[22, 23],
       [29, 30]])

### 结构化脚标工具（Structural indexing tools）

In [91]:
y.shape

(5, 7)

In [92]:
y[:,np.newaxis,:].shape# 并没有元素在这个维度上，只是为了增加维度

(5, 1, 7)

In [93]:
x=np.arange(5)

In [94]:
x[:,np.newaxis]+x[np.newaxis,:]

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

### 设置指定脚标的值（Assigning values to indexed arrays）

In [95]:
x=np.arange(10)

In [96]:
x[2:7]=1
x

array([0, 1, 1, 1, 1, 1, 1, 7, 8, 9])

In [97]:
x[2:7]=np.arange(5)
x

array([0, 1, 0, 1, 2, 3, 4, 7, 8, 9])

- 如果将整型数组设置浮点数的值，或者是复数值，将会产生精度损失，甚至引发异常

In [98]:
x[1]=1.2

In [99]:
x[1]

1

In [100]:
x[1]=1j

TypeError: can't convert complex to int

### 处理畸变的切片数量

In [101]:
z=np.arange(81).reshape(3,3,3,3)

In [102]:
indices=(1,1,1,1)

In [103]:
z[indices]

40

In [104]:
indices=(1,1,1,slice(0,2))

In [105]:
z[indices]

array([39, 40])

In [106]:
indices=(1,Ellipsis,1) #Ellipsis等同于....又等同于：：

In [107]:
z[indices]

array([[28, 31, 34],
       [37, 40, 43],
       [46, 49, 52]])

In [108]:
z[1,:,:,1]

array([[28, 31, 34],
       [37, 40, 43],
       [46, 49, 52]])

## 广播（Broadcasting）

- 术语“广播”是用来描述不同形状数组进行数学运算的一种操作方式

In [109]:
a=np.array([1,2,3])
b=np.array([2,3,4])
a*b

array([ 2,  6, 12])

In [110]:
a=np.array([1.2,3.4,5.6])
b=2
a*b

array([  2.4,   6.8,  11.2])

 ### 广播的一般规则

当我们对两个数组进行操作时，Numpy会先对数组的形状进行比较。最先开始比较最后的维度，接着比较倒数第二个维度...，直到比较完成

- 数组不是必须是相同的维数例如：
    - Image  (3d array):256  256  3
    
      Scale （1d array:       3
      
      Result (3d array):256  256  3

- 我们再来举一个通用的小例子：我们有A和B两个数组

A    (4d Array):  8  1  6  1

B    (3d Array):    7  1  5

Result (4d Array): 8  7  6  5

In [111]:
x=np.arange(4)
xx=x.reshape(4,1)

In [112]:
y=np.ones(5)

In [113]:
z=np.ones((3,4))

In [114]:
x.shape

(4,)

In [115]:
y.shape

(5,)

In [116]:
x+y

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [ ]:
xx.shape

In [ ]:
(xx+y).shape

In [ ]:
xx+y

In [ ]:
x.shape

In [ ]:
z.shape

In [ ]:
x+z

In [ ]:
a=np.array([0.,10.,20.,30.])
b=np.array([1.,2.,3.])

In [ ]:
a[:,np.newaxis]+b# np.newaxis使a的形状变为（4,1）

##  结构数组（Structured Arrays）

- 小例子

In [ ]:
x=np.array([(1,2.,"Hello"),
           (2,3.,"World")],dtype=[("foo","i4"),("bar","f4"),("baz","S10")])

In [ ]:
x

In [ ]:
x[1]

In [ ]:
y=x["bar"]

In [ ]:
y

In [ ]:
y[:]=y*2

In [ ]:
y

- 注意：y数组只是一个view，并不是一个copy，当我们改变x的值的时候，y的值也会变

In [ ]:
x[1]=(-1,-1.,"master")

In [ ]:
x

In [ ]:
y

### 定义结构数据

- String argument

In [ ]:
x=np.zeros(3,dtype="3int8,float32,(2,3)float64")

In [ ]:
x

- Tuple argument

In [ ]:
x=np.zeros(3,dtype=("i 4",[("r","u1"),("g","u1"),("b","u1"),("a","u1")]))

In [ ]:
x['r']

In [ ]:
x["a"]

- List argument

In [ ]:
x=np.zeros(3,dtype=[("x","f4"),("y",np.float32),("value","f4",(3,3))])

In [ ]:
x

- Dictionary argument

In [ ]:
x=np.zeros(3,dtype={"names":["col1","col2"],"formats":["i4","f4"]})

In [ ]:
x

### 访问权限和名字修改

In [ ]:
x.dtype.names

In [ ]:
x.dtype.names=["x","y"]

In [ ]:
x

 ### 一次访问多重区域

In [ ]:
x=np.array([(15,2.5,(1.,2.)),
            (3.,4.,(4.,5.)),
           (1.,3.,(2.,6.))],dtype=[("x","f4"),("y",np.float32),("value","f4",(2,2))])

In [ ]:
x

In [ ]:
x[["x",'y']]

In [ ]:
x[["x","value"]]

In [ ]:
x[["y","x"]]

### 填充结构数组

In [ ]:
arr=np.zeros((5,),dtype=[("var1","f8"),("var2","f8")])

In [ ]:
arr

In [ ]:
arr["var1"]=np.arange(5)

In [ ]:
arr

In [ ]:
arr["var1"]

In [ ]:
arr[0]

In [ ]:
arr[0]=(10,20)

In [ ]:
arr

### 记录数组

- 记录数组，Numpy提供了一个记录数组的类型：__numpy.rec.array__:

In [ ]:
recordarr=np.rec.array([(1,2.,"Hello"),(2,3.,"World")],dtype=[("foo","i4"),("bar","f4"),
                                                             ("baz","S10")])

In [ ]:
recordarr.bar

In [ ]:
recordarr[1:2]

In [ ]:
recordarr[1:2].foo

In [ ]:
recordarr.foo[1:2]

In [ ]:
recordarr[1].baz

In [ ]:
arr=np.array([(1,2.,"Hello"),(2,3.,"World")],dtype=[("foo","i4"),("bar","f4"),
                                                             ("baz","S10")])

In [ ]:
recordarr=np.rec.array(arr)

In [ ]:
recordarr


In [ ]:
type(recordarr)

 # Cython（提高计算效率，Numpy的利器）

In [ ]:
%pwd